const sections=[['⌂','Dashboard'],['🚕','Bookings'],['📍','Live GPS'],['🚗','Drivers'],['👥','Customers'],['🚘','Cars'],['📄','Documents'],['€','Pricing'],['%','Commission'],['💳','Payments'],['↩','Refunds'],['🏷','Promotions'],['🎫','Support'],['📊','Revenue'],['🤖','AI Assistant'],['⚙','Settings']];
const nav=document.getElementById('nav'),app=document.getElementById('app'),title=document.getElementById('title');
const state={stats:null,loading:false,error:null};
sections.forEach(([icon,name],i)=>{const b=document.createElement('button');b.innerHTML=`${icon} &nbsp; ${name}`;b.onclick=()=>render(name,b);if(i===0)b.classList.add('active');nav.appendChild(b)});
function card(label,value,sub='Live Supabase data'){return `<div class="card"><div class="label">${label}</div><div class="num">${value ?? '—'}</div><div class="muted">${sub}</div></div>`}
function money(v){return v==null?'—':new Intl.NumberFormat('fr-FR',{style:'currency',currency:'EUR'}).format(Number(v)||0)}
async function loadStats(){state.loading=true;state.error=null;renderDashboard();try{const token=localStorage.getItem('vasi_admin_access_token')||'';const r=await fetch('/api/admin-stats',{headers:{Authorization:`Bearer ${token}`}});const data=await r.json();if(!r.ok)throw new Error(data.error||'Unable to load admin data');state.stats=data}catch(e){state.error=e.message}finally{state.loading=false;renderDashboard()}}
function render(name,button){document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));button.classList.add('active');title.textContent=name;const s=state.stats||{};const data={
Bookings:[['Total bookings',s.bookings],['Bookings today',s.bookingToday],['Active rides',s.activeRides],['Completed today',s.completedToday]],
Drivers:[['Total drivers',s.drivers],['Online drivers',s.onlineDrivers],['Verified drivers',s.verifiedDrivers],['Pending documents',s.pendingDocuments]],
Customers:[['Registered customers',s.customers],['Bookings today',s.bookingToday],['Active rides',s.activeRides],['Support cases','—']],
Cars:[['Active vehicles','—'],['Available','—'],['Maintenance','—'],['Insurance expiring','—']],
Documents:[['Total documents',s.documents],['Pending review',s.pendingDocuments],['Approved','—'],['Expiring soon','—']],
Payments:[['Payment records',s.payments],['Payments today',s.paymentToday],['Today collected',money(s.todayPaymentsAmount)],['Refund requests','—']],
Refunds:[['Pending','—'],['Approved today','—'],['Rejected','—'],['Total refunded','—']],
Promotions:[['Active coupons','—'],['Redemptions today','—'],['Scheduled','—'],['Expired','—']],
Support:[['Open tickets','—'],['Urgent','—'],['Awaiting driver','—'],['Resolved today','—']],
Revenue:[['Gross today',money(s.todayGross)],['Driver amount today',money(s.todayDriverAmount)],['VASI commission today',money(s.todayCommission)],['Refunds','—']],
Pricing:[['Base fare','—'],['Per km','—'],['Per minute','—'],['Airport surcharge','—']],
Commission:[['Default rate','—'],['Driver earnings today',money(s.todayDriverAmount)],['Platform share today',money(s.todayCommission)],['Pending payout','—']],
['Live GPS']:[['Drivers online',s.onlineDrivers],['Trips active',s.activeRides],['SOS alerts','—'],['GPS health','—']],
['AI Assistant']:[['Open conversations','—'],['Resolved by AI','—'],['Escalated','—'],['AI availability','—']],
Settings:[['Admin users','—'],['Roles','—'],['Regions','France / Europe'],['Audit events','—']]}[name]||[];
app.innerHTML=`<div class="grid">${data.map(([x,v])=>card(x,v)).join('')}</div><div class="panel"><h3>${name} operations</h3><div class="actions"><button class="btn" onclick="loadStats()">Refresh live data</button><button class="btn">Export report</button></div><div class="row"><span>Supabase backend</span><span class="pill">${state.error?'Unavailable':'Connected'}</span></div><div class="row"><span>Authentication</span><span class="pill">Admin protected</span></div><div class="row"><span>Data source</span><span class="pill">Production database</span></div></div>`}
function renderDashboard(){const s=state.stats||{};title.textContent='Dashboard';const notice=state.error?`<div class="panel"><h3>Admin data connection</h3><p class="muted">${state.error}</p><p class="muted">Set VASI_SUPABASE_URL and SUPABASE_SERVICE_ROLE_KEY in Vercel, then sign in through the Admin login.</p></div>`:'';app.innerHTML=`<div class="grid">${card('Drivers',s.drivers)}${card('Customers',s.customers)}${card('Bookings',s.bookings)}${card('Active rides',s.activeRides)}${card('Online drivers',s.onlineDrivers)}${card('Pending documents',s.pendingDocuments)}${card('Payments',s.payments)}${card('Gross today',money(s.todayGross))}</div>${notice}<div class="panel"><h3>Operations overview</h3><div class="row"><span>Verified drivers</span><span class="pill">${s.verifiedDrivers??'—'}</span></div><div class="row"><span>Completed rides today</span><span class="pill">${s.completedToday??'—'}</span></div><div class="row"><span>VASI commission today</span><span class="pill">${money(s.todayCommission)}</span></div><div class="row"><span>Driver earnings today</span><span class="pill">${money(s.todayDriverAmount)}</span></div></div>`}
window.loadStats=loadStats;renderDashboard();loadStats();