const url=process.env.VASI_SUPABASE_URL||process.env.SUPABASE_URL||'https://vhfyvkrvysrooaqzcxsp.supabase.co';
const publicKey=process.env.VASI_SUPABASE_ANON_KEY||process.env.SUPABASE_ANON_KEY||'sb_publishable_mypiW8lczhmoQb4rECuE8Q_dEhNiCKT';
const key=publicKey;
const h=()=>({apikey:key,Authorization:`Bearer ${key}`});
async function db(path,options={}){const r=await fetch(`${url}/rest/v1/${path}`,{...options,headers:{...h(),...(options.headers||{})}}),d=await r.json().catch(()=>null);if(!r.ok)throw new Error(d?.message||'Database request failed');return d}
async function catalog(){if(!key)throw new Error('Restaurant service is not configured');const rs=await db('restaurants?select=id,name,cuisine,preparation_minutes,minimum_order,delivery_fee,delivery_mode&status=eq.approved&active=eq.true&is_open=eq.true&order=name.asc');if(!rs.length)return[];const items=await db(`restaurant_menu_items?select=id,restaurant_id,name,description,category,price,allergens,photo_url&active=eq.true&restaurant_id=in.(${rs.map(x=>x.id).join(',')})&order=sort_order.asc,name.asc`);return rs.map(r=>({...r,icon:'🍽️',eta:`${r.preparation_minutes}–${r.preparation_minutes+10} min`,items:items.filter(i=>i.restaurant_id===r.id).map(i=>({...i,price:Number(i.price)}))})).filter(r=>r.items.length)}
async function price(body){const r=(await catalog()).find(x=>x.id===String(body.restaurant_id||''));if(!r)throw new Error('Restaurant is closed or unavailable');const requested=Array.isArray(body.items)?body.items:[];if(!requested.length||requested.length>20)throw new Error('Choose at least one valid item');const items=requested.map(e=>{const m=r.items.find(i=>i.id===String(e.id||'')),q=Number(e.quantity);if(!m||!Number.isInteger(q)||q<1||q>10)throw new Error('Invalid basket item');return{id:m.id,name:m.name,price:m.price,quantity:q,line_total:Number((m.price*q).toFixed(2))}});const subtotal=Number(items.reduce((s,i)=>s+i.line_total,0).toFixed(2));if(subtotal<Number(r.minimum_order||0))throw new Error(`Minimum order is €${Number(r.minimum_order).toFixed(2)}`);const fee=Number(r.delivery_fee||0);return{restaurant:r,items,subtotal,delivery_fee:fee,total:Number((subtotal+fee).toFixed(2)),currency:'EUR'}}
async function user(auth){if(!auth.startsWith('Bearer '))return null;const r=await fetch(`${url}/auth/v1/user`,{headers:{apikey:publicKey,Authorization:auth}});if(!r.ok)return null;const u=await r.json();return u?.id?u:null}
async function address(v){const a=String(v||'').trim().slice(0,200);if(a.length<6)throw new Error('Enter a valid full delivery address');const q=new URLSearchParams({format:'jsonv2',limit:'1',countrycodes:'fr,gb,be,de,nl,lu,ch,es,it,pt',q:a}),r=await fetch(`https://nominatim.openstreetmap.org/search?${q}`,{headers:{'User-Agent':'VASI/1.0 (eats-checkout)'}});if(!r.ok)throw new Error('Address search is temporarily unavailable');const m=(await r.json())?.[0];if(!m)throw new Error('Delivery address not found');return m.display_name||a}
export default async function handler(req,res){res.setHeader('Cache-Control','no-store');try{if(req.method==='GET')return res.status(200).json({restaurants:await catalog(),mode:'partner_catalog'});if(req.method!=='POST')return res.status(405).json({error:'GET or POST required'});const b=typeof req.body==='string'?JSON.parse(req.body||'{}'):req.body||{},p=await price(b);if(b.action!=='book')return res.status(200).json(p);const auth=req.headers.authorization||'',u=await user(auth);if(!u)return res.status(401).json({error:'Login required'});const delivery_address=await address(b.delivery_address);const rows=await db('eats_orders',{method:'POST',headers:{Authorization:auth,'Content-Type':'application/json',Prefer:'return=representation'},body:JSON.stringify({customer_id:u.id,restaurant_id:p.restaurant.id,restaurant_name:p.restaurant.name,items:p.items,delivery_address,subtotal:p.subtotal,delivery_fee:p.delivery_fee,total:p.total,currency:p.currency,status:'pending'})});return res.status(201).json({...p,delivery_address,order_id:rows[0]?.id||null})}catch(e){const m=e?.message||'Eats service error';return res.status(/invalid|choose|address|minimum|closed|unavailable/i.test(m)?400:502).json({error:m})}}
